steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-f', 'findvacancies-web-thymeleaf/Dockerfile', '-t', 'gcr.io/$PROJECT_ID/findvacancies-thymeleaf:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/findvacancies-thymeleaf:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'findvacancies-thymeleaf'
    - '--image'
    - 'gcr.io/$PROJECT_ID/findvacancies-thymeleaf:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - 'gcr.io/$PROJECT_ID/findvacancies-thymeleaf:$COMMIT_SHA'