#
steps:
  - name: 'maven:3.6.0-jdk-11-slim'
    args:
      - clean
      - install
      - '-DskipTests'
    entrypoint: mvn
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        europe-central2-docker.pkg.dev/$PROJECT_ID/find-vacancies-repo/find_vacancies:$COMMIT_SHA
      - '-t'
      - >-
        europe-central2-docker.pkg.dev/$PROJECT_ID/find-vacancies-repo/find_vacancies:latest
      - .
  - name: gcr.io/cloud-builders/kubectl
    env:
      - CLOUDSDK_COMPUTE_ZONE=europe-central2-a
      - CLOUDSDK_CONTAINER_CLUSTER=cloudx-cluster
    args:
      - apply
      - '-f'
      - k8s/
  - name: gcr.io/cloud-builders/kubectl
    env:
      - CLOUDSDK_COMPUTE_ZONE=europe-central2-a
      - CLOUDSDK_CONTAINER_CLUSTER=cloudx-cluster
    args:
      - set
      - image
      - deployment
      - find-vacancies
      - >-
        find-vacancies=europe-central2-docker.pkg.dev/$PROJECT_ID/find-vacancies-repo/find_vacancies:$COMMIT_SHA
images:
  - >-
    europe-central2-docker.pkg.dev/$PROJECT_ID/find-vacancies-repo/find_vacancies:$COMMIT_SHA
  - >-
    europe-central2-docker.pkg.dev/$PROJECT_ID/find-vacancies-repo/find_vacancies:latest
