version: "3.8"

services:
  app-thymeleaf:
    build:
      context: .
      dockerfile: ./findvacancies-web-thymeleaf/Dockerfile
    restart: on-failure
    env_file: ./.env
    ports:
      - "8082:8080"
    volumes:
      - .m2:/root/.m2
    #stdin_open: true
    #tty: true

  app-rest:
    build:
      context: .
      dockerfile: ./findvacancies-web-rest/Dockerfile
    restart: on-failure
    env_file: ./.env
    ports:
      - "8083:8080"
    volumes:
      - .m2:/root/.m2
    #stdin_open: true
    #tty: true

  app-vaadin:
    build:
      context: .
      dockerfile: ./findvacancies-web-vaadin/Dockerfile
    restart: on-failure
    env_file: ./.env
    ports:
      - "8084:8080"
    volumes:
      - .m2:/root/.m2
    #stdin_open: true
    #tty: true



