version: 2.1

orbs:
  maven: circleci/maven@1.3

build:
  #working_directory: /tmp
  steps:
    - run:
        name: Creating Dummy Artifacts
        command: |
          echo "my artifact file" > /findvacancies/target;
    - store_artifacts:
        path: /findvacancies/target
        destination: FindVacancies

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results