version: 2.1
executors:
  java17:
    docker:
      - image: 'cimg/openjdk:17.0'
orbs:
  maven: circleci/maven@1.3.0
  node: circleci/node@5.1.0

build:
  steps:
    - run:
        name: Creating Dummy Artifacts
        command: |
          echo "my artifact file" > /findvacancies/target;
    - store_artifacts:
        path: /findvacancies/target
        destination: FindVacancies

#workflows:
#  maven_test:
#    jobs:
#      # checkout, build, test, and upload test results
#      - maven/test
workflows:
  maven_test:
    jobs:
      - maven/test:
          command: '-X clean install'
          executor: java17