apiVersion: apps/v1
kind: Deployment
metadata:
  name: find-vacancies
  labels:
    run: find-vacancies
spec:
  replicas: 2
  selector:
    matchLabels:
      run: find-vacancies
  template:
    metadata:
      labels:
        run: find-vacancies
    spec:
      serviceAccountName: sa-cloud-sql
      containers:
        - name: "find-vacancies"
          image: "europe-central2-docker.pkg.dev/cloudx-353214/find-vacancies-repo/find_vacancies:latest"
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
                  optional: false
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
                  optional: false
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: database
                  optional: false
        - name: cloud-sql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.31.0
          command:
            - "/cloud_sql_proxy"
            - "-ip_address_types=PRIVATE"
            - "-log_debug_stdout"
            - "-instances=cloudx-353214:us-central1:cloudx-db-01=tcp:3306"
            - "-credential_file=/secrets/service_account.json"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /secrets/
              name: secret-volume
              readOnly: true
      volumes:
        - name: secret-volume
          secret:
            secretName: sql-sa-secret