
FROM tomcat:10.1-jdk17-openjdk-slim
RUN mv /usr/local/tomcat/webapps.dist/* /usr/local/tomcat/webapps/
ADD /findvacancies-web-jsp/target/find-vacancies-jsp*.war /usr/local/tomcat/webapps/

EXPOSE 8080

CMD chmod +x /usr/local/tomcat/bin/catalina.sh
CMD ["catalina.sh", "run"]
